### PR TITLE
Refactor Broadcast and fix tx.Sign w/ non-cosmos bech32

### LINKED ISSUE #12: New broadcast mode
We should make a new broadcast function for transactions that blocks until a TX sent _is_ included into a block. This would make many applications much easier to write: block till my state is included. Weapons at our disposal:
- Mempool queries (i.e. look in the mempool of the node you submitted the tx to and return when you see the tx leave)
- Block subscriptions (i.e. listen for new blocks and return only when we see a transaction included)
- Transaction hash queries (i.e. query on a loop for the transaction you just sent and return when you see it included)

This could completely replace the broadcast mode block method we are using currently. Would make relayer code much easier to write.

### PR DESCRIPTION
**Pull request by jackzampolin**
Closes #12

### CODE REVIEW

File: client/broadcast.go [hunk 1]
```diff
@@ -16,48 +20,83 @@ import (
 // an intermediate structure which is logged if the context has a logger
 // defined.
 func (cc *ChainClient) BroadcastTx(ctx context.Context, tx []byte) (res *sdk.TxResponse, err error) {
```
Comment (jackzampolin) [inline client/broadcast.go:22]: Would love some 👀 here

File: client/hack.go [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+
+// This file is cursed and this mutex is too
+// you don't want none of this dewey cox
+var sdkConfigMutex sync.Mutex
+
+// SetSDKConfig sets the SDK config to the proper bech32 prefixes
+// Don't use this unless you know what you're doing.
+// if lens is successful, this can be eliminated
+// TODO: :dagger: :knife: :chainsaw: remove this function
+func (cc *ChainClient) SetSDKContext() func() {
```
Comment (marbar3778) [inline client/hack.go:17]: can we move this to internal so someone doesn't accidentally start using it?
